const Institution = require("../models/Institution");

// auto-generate initials here
const generateInitialsFromName = (instituteName) => {
  if (!instituteName) return '';
  const skipWords = ['of', 'and', 'the', 'for', '&', 'a', 'an', 'in', 'at', 'to'];
  const words = instituteName
    .trim()
    .split(/\s+/)
    .filter(word => {
      const lowerWord = word.toLowerCase();
      return word.length > 0 && !skipWords.includes(lowerWord);
    });
  const initials = words
    .map(word => word.charAt(0).toUpperCase())
    .join('');
  
  return initials;
};

// Suggest initials based on institution name
const suggestInitials = async (req, res) => {
  try {
    const institution = req.school;
    
    if (!institution) {
      return res.status(404).json({
        success: false,
        message: "Institution not found"
      });
    }

    const suggestedInitials = generateInitialsFromName(institution.institute_name);
    
    return res.status(200).json({
      success: true,
      instituteName: institution.institute_name,
      suggestedInitials,
      currentInitials: institution.initials || null,
      message: suggestedInitials ? `Suggested initials: ${suggestedInitials}` : "Could not generate initials from institution name"
    });

  } catch (error) {
    console.error("Error suggesting initials:", error);
    return res.status(500).json({
      success: false,
      message: "Server error while suggesting initials",
      error: error.message
    });
  }
};

// Manually update initials if autogeneration is nto needed.
const updateInitials = async (req, res) => {
  try {
    const institutionId = req.school._id;
    const { initials, useAutoGenerated } = req.body;
    
    const institution = await Institution.findById(institutionId);
    
    if (!institution) {
      return res.status(404).json({
        success: false,
        message: "Institution not found"
      });
    }

    let finalInitials;

    if (useAutoGenerated) {
      finalInitials = generateInitialsFromName(institution.institute_name);
      
      if (!finalInitials) {
        return res.status(400).json({
          success: false,
          message: "Could not auto-generate initials from institution name"
        });
      }
    } else if (initials) {
      // Validate: only letters, 2-10 characters
      const cleanInitials = initials.trim().toUpperCase();
      
      if (!/^[A-Z]{2,10}$/.test(cleanInitials)) {
        return res.status(400).json({
          success: false,
          message: "Initials must be 2-10 letters only (no numbers or special characters)"
        });
      }
      finalInitials = cleanInitials;
    } else {
      return res.status(400).json({
        success: false,
        message: "Please provide 'initials' or set 'useAutoGenerated: true'"
      });
    }

    //Check if initials already exist for another institution
    const existingInstitution = await Institution.findOne({ 
      initials: finalInitials,
      _id: { $ne: institutionId }
    });

    if (existingInstitution) {
      return res.status(409).json({
        success: false,
        message: `Initials '${finalInitials}' are already taken by another institution`,
        suggestion: `Try adding a number or letter, e.g., ${finalInitials}2 or ${finalInitials}K`
      });
    }

    const updatedInstitution = await Institution.findByIdAndUpdate(
      institutionId,
      { $set: { initials: finalInitials } },
      { new: true, runValidators: false }
    );

    return res.status(200).json({
      success: true,
      message: "Initials updated successfully",
      institution: {
        id: updatedInstitution._id,
        instituteName: updatedInstitution.institute_name,
        initials: updatedInstitution.initials,
        institutionType: updatedInstitution.institution_type
      }
    });

  } catch (error) {
    console.error("Error updating initials:", error);
    return res.status(500).json({
      success: false,
      message: "Server error while updating initials",
      error: error.message
    });
  }
};

// Get institution profile
const getProfile = async (req, res) => {
  try {
    const institution = req.school;
    
    if (!institution) {
      return res.status(404).json({
        success: false,
        message: "Institution not found"
      });
    }

    return res.status(200).json({
      success: true,
      institution: {
        id: institution._id,
        instituteName: institution.institute_name,
        email: institution.email,
        phone: institution.phone,
        address: institution.address,
        headOfInstitute: institution.head_of_institute,
        institutionType: institution.user_type,
        initials: institution.initials || null,
        suggestedInitials: generateInitialsFromName(institution.institute_name),
        createdAt: institution.createdAt
      }
    });

  } catch (error) {
    console.error("Error fetching profile:", error);
    return res.status(500).json({
      success: false,
      message: "Server error while fetching profile",
      error: error.message
    });
  }
};

// not needed anymore, but keeping for future use if institution type needs to be updated.
const updateInstitutionType = async (req, res) => {
  try {
    const institutionId = req.school._id;
    const { institutionType } = req.body;
    
    if (!institutionType || !['school', 'college'].includes(institutionType)) {
      return res.status(400).json({
        success: false,
        message: "institutionType must be 'school' or 'college'"
      });
    }

    const updatedInstitution = await Institution.findByIdAndUpdate(
      institutionId,
      { $set: { user_type: institutionType } },
      { new: true, runValidators: false }
    );

    if (!updatedInstitution) {
      return res.status(404).json({
        success: false,
        message: "Institution not found"
      });
    }

    return res.status(200).json({
      success: true,
      message: "Institution type updated successfully",
      institution: {
        id: updatedInstitution._id,
        instituteName: updatedInstitution.institute_name,
        institutionType: updatedInstitution.user_type
      }
    });

  } catch (error) {
    console.error("Error updating institution type:", error);
    return res.status(500).json({
      success: false,
      message: "Server error while updating institution type",
      error: error.message
    });
  }
};

module.exports = {
  generateInitialsFromName,
  suggestInitials,
  updateInitials,
  updateInstitutionType,
  getProfile
};
